# Numpy->Numerical Python
* foundations for mathematical prob,scientic,numerical prob,
* homo multidimensional array
#### Topics
* Creation of 1D,2D,3D Arrays
* Attributes -> ndim,size,dtype,shape,type
* Methods->arange,linspace,ravel,random
* Stacking->hstack,vstack
* Splitting-> hsplit,vsplit
* Broadcasting, Boolean masking 
* Others-> zeros,ones,eye,max,min,copy

In [5]:
!pip install numpy

In [4]:
import numpy as np

In [7]:
#get version
print(np.__version__)

1.19.2


In [8]:
##Array creation with 0 dim --> point
arr=np.array(1)
arr

array(1)

In [19]:
#Create a 1D array
d1 = np.array([3,4,5,8,9])
d1
#d2 = np.array(['a','b'])
#d2    #data type is printed as it is a string. encoding UTF

array([3, 4, 5, 8, 9])

In [14]:
print("The dimension",d1.ndim)   #no of dimensions in the array
print("The size",d1.size)    #no. of elements
print("The datatype",d1.dtype)   #data type of elements
print("The type",type(d1))   #type of d1 --> ndarray
print("Shape",d1.shape) #no of rows and col in the array
print()
print("The dimension",d2.ndim)   
print("The size",d2.size)   
print("The datatype",d2.dtype)   
print("The type",type(d2))   
print("Shape",d2.shape)

The dimension 1
The size 5
The datatype int32
The type <class 'numpy.ndarray'>
Shape (5,)

The dimension 1
The size 2
The datatype <U1
The type <class 'numpy.ndarray'>
Shape (2,)


In [20]:
d0 = np.array((1,2,3))
print(d0)
type(d0) #tuple given to an array hence data type is array

[1 2 3]


numpy.ndarray

In [23]:
#CREAte 2D array
d2 = np.array([[1,2,3],[3,4,7]])
print(d2)
type(d2)

[[1 2 3]
 [3 4 7]]


numpy.ndarray

In [ ]:
print("The shape is",d2.shape)

In [ ]:
print("The dimension",d2.ndim)
print("The size",d2.size)
print("The datatype",d2.dtype)
print("The type",type(d2))

In [ ]:
#Creating a 3D Array
d3 = np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]]])
d3

In [ ]:
print("The dimension",d3.ndim)
print("The size",d3.size)
print("The datatype",d3.dtype)
print("The type",type(d3))
print("The shape is",d3.shape) #(3d,2d,1d)

# Methods
* arange->similar to range
* linspace
* ravel
* random

In [ ]:
np.arange(5) #stop

In [ ]:
np.arange(1,5) # start,stop

In [ ]:
np.arange(1,10,1) #start,stop,step

In [ ]:
np.arange(50,100,5)

In [ ]:
np.arange(50,100,5).reshape(2,5)

In [ ]:
np.arange(50,100,5).reshape(5,2)

In [ ]:
np.arange(50,100,5).reshape(5,1,2)

In [ ]:
np.arange(50,100,5).reshape(1,1,2,5)

In [ ]:
np.arange(1,16).reshape(3,5)

In [ ]:
#linspace ->start,stop,no.of elements->(stop-Included)
np.linspace(1,50,10)

In [ ]:
np.linspace(1,50,10,retstep=True)

In [5]:
#ravel converts array of any dim to a single (1D )
a2 = np.arange(50).reshape(5,5,2)
a2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [6]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
# create 2d array and convert it into 1D
d2=np.array([[1,2,3],[4,6,7]])
dr
#dr.ravel()

In [14]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
ar1=np.array([l1,l2,l3])
ar1
ar1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#random->create random nos->rand->(0,1)
np.random.rand(5)

array([0.66357044, 0.54857094, 0.90385041, 0.42623885, 0.44024578])

In [15]:
np.random.rand(5)*100

array([90.56929031, 34.0106944 ,  4.50243756, 27.46580573, 49.62335748])

In [24]:
np.random.randint(5) #int random no 0 to 4

1

In [32]:
np.random.randint(1,5) #int 1 to 4

3

In [22]:
np.random.rand(10).reshape(5,2)

array([[0.8759766 , 0.84867989],
       [0.47903449, 0.17883009],
       [0.72287827, 0.04617578],
       [0.37971333, 0.4975454 ],
       [0.95137894, 0.98767874]])

In [ ]:
np.linspace(1,5,4,retstep=True)

In [ ]:
a=np.linspace(0,50,11,retstep=True,dtype=str)
a

In [ ]:
a=np.linspace(1,50,5)

In [ ]:
a

In [ ]:
type(a)

In [ ]:
a=np.linspace(0,50,11)
type(a)
a

In [ ]:
np.random.randint(1,50,5)

# Stacking
* hstack
* vstack

In [ ]:
a1= np.arange(10,50).reshape(10,4)
a1

In [ ]:
a2=np.linspace(10,50,40).reshape(10,4)
a2

In [ ]:
type(a2)

In [ ]:
a2.dtype

In [ ]:
a1

In [ ]:
a2

In [ ]:
np.hstack((a1,a2))

In [ ]:
np.vstack((a1,a2))

In [ ]:
#Create 2 arrays, 1st array->15(0-14) 2nd array->15(20-34)
# Use hstack and vstack
ab1=np.arange(15).reshape(5,3)
ab2=np.arange(20,35).reshape(5,3)
print(ab1)
print(ab2)

In [ ]:
np.hstack((ab1,ab2))

In [ ]:
np.vstack((ab1,ab2))

In [ ]:
np.hstack((ab1,ab2,ab1))

In [ ]:
a = np.arange(15).reshape(3,5)
a

In [ ]:
#Split->hsplit,vsplit
ab1

In [ ]:
ab2

In [ ]:
np.hsplit(ab1,3)

In [ ]:
np.vsplit(ab1,5)

In [ ]:
a3=np.arange(24).reshape(6,4)
a3

In [ ]:
np.hsplit(a3,2)

In [ ]:
np.hsplit(a3,4)

In [ ]:
a3

In [ ]:
np.vsplit(a3,3)

In [ ]:
np.vsplit(a3,2)

In [ ]:
np.vsplit(a3,6)

In [ ]:
a10 = np.arange(24).reshape(2,3,4)
a11= np.hsplit(a10,3)
print(a10)
print(a11)


In [ ]:
# Broadcasting 
a3

In [ ]:
a3[0:2,]=50

In [ ]:
a3

In [ ]:
a3[4:,1:3]=50
a3

In [ ]:
ab1

In [ ]:
# 2nd & 3rd column replace with 100
ab1[:,1:3] = 100
ab1

In [ ]:
ab1[4:,2:] = 50
ab1

In [ ]:
# Boolean Masking
ab1

In [ ]:
re = 0 == ab1%2 # re= ab1%2==0

In [ ]:
ab1[re]

In [ ]:
re

In [ ]:
re1 = 0 == ab1%3
re1

In [ ]:
#zeros,ones,eye,max,min,copy
np.zeros(2)

In [ ]:
np.zeros((2,2))

In [ ]:
np.ones((2,3),dtype=int)

In [ ]:
np.eye(3)

In [ ]:
np.eye(5)

In [ ]:
ab1

In [ ]:
np.max(ab1)

In [ ]:
np.min(ab1)

In [ ]:
ab3=ab1.copy()
ab3

In [ ]:
np.eye(5)*5

In [ ]:
ab4=ab1

In [ ]:
ab4

In [ ]:
ab1

In [ ]:
ab4

In [ ]:
b=ab1+ab4
b

In [ ]:
c=ab1-ab4
c