# Numpy->Numerical Python
* foundations for mathematical prob,scientic,numerical prob,
* homo multidimensional array
#### Topics
* Creation of 1D,2D,3D Arrays
* Attributes -> ndim,size,dtype,shape,type
* Methods->arange,linspace,ravel,random
* Stacking->hstack,vstack
* Splitting-> hsplit,vsplit
* Broadcasting, Boolean masking 
* Others-> zeros,ones,eye,max,min,copy

In [1]:
## installation of package
!pip install numpy

In [2]:
## importing the library
import numpy  as np

In [3]:
## Getting version

print(np.__version__)

1.18.5


In [12]:
## Array creation with 0 dim
arr=np.array(1) ## array with Zero dimension -->point
arr

array(1)

In [13]:
#Create a 1D array
d1 = np.array([3,4,5,8,9])
d1

array([3, 4, 5, 8, 9])

In [14]:
## Array summary
print("The dimension",d1.ndim)
print("The size",d1.size)
print("The datatype",d1.dtype)
print("The type",type(d1))
print("Shape",d1.shape)

The dimension 1
The size 5
The datatype int32
The type <class 'numpy.ndarray'>
Shape (5,)


In [22]:
a_tuple = ([(15 , 23, 3)])
type(a_tuple)


list

In [28]:
a_tuple =np.array((15 , 23, 3))
a_tuple



array([15, 23,  3])

In [29]:
#CREAte 2D array
d2 = np.array([[1,2,3],[3,4,7]])
d2

array([[1, 2, 3],
       [3, 4, 7]])

In [ ]:
print("The shape is",d2.shape)

In [ ]:
print("The dimension",d2.ndim)
print("The size",d2.size)
print("The datatype",d2.dtype)
print("The type",type(d2))

In [30]:
arr_2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12,]])
arr_2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
#Creating a 3D Array
d3 = np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]]])
d3

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[4, 5],
        [5, 6],
        [6, 7]]])

In [32]:
print("The dimension",d3.ndim)
print("The size",d3.size)
print("The datatype",d3.dtype)
print("The type",type(d3))
print("The shape is",d3.shape) #(3d,2d,1d)

The dimension 3
The size 12
The datatype int32
The type <class 'numpy.ndarray'>
The shape is (2, 3, 2)


# Methods
* arange->similar to range
* linspace
* ravel
* random

In [35]:
np.arange(5) #stop

array([0, 1, 2, 3, 4])

In [36]:
np.arange(1,5) # start,stop

array([1, 2, 3, 4])

In [37]:
np.arange(1,10,2) #start,stop,step

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(50,100,5)

In [43]:
np.arange(50,100,5).reshape(5,2)  ##5 rows and 2 columns

array([[50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [ ]:
np.arange(50,100,5).reshape(5,2)

In [44]:
np.arange(50,100,5).reshape(5,1,2) ## reshaping to 3rd dimension

array([[[50, 55]],

       [[60, 65]],

       [[70, 75]],

       [[80, 85]],

       [[90, 95]]])

In [45]:
np.arange(50,100,5).reshape(1,1,2,5) ## reshaping to 4 the dimension

array([[[[50, 55, 60, 65, 70],
         [75, 80, 85, 90, 95]]]])

In [47]:
np.arange(1,17).reshape(3,5)

ValueError: cannot reshape array of size 16 into shape (3,5)

In [55]:
#linspace ->start,stop,no.of elements->(stop-Included)
np.linspace(1,50,90)

array([ 1.        ,  1.5505618 ,  2.1011236 ,  2.65168539,  3.20224719,
        3.75280899,  4.30337079,  4.85393258,  5.40449438,  5.95505618,
        6.50561798,  7.05617978,  7.60674157,  8.15730337,  8.70786517,
        9.25842697,  9.80898876, 10.35955056, 10.91011236, 11.46067416,
       12.01123596, 12.56179775, 13.11235955, 13.66292135, 14.21348315,
       14.76404494, 15.31460674, 15.86516854, 16.41573034, 16.96629213,
       17.51685393, 18.06741573, 18.61797753, 19.16853933, 19.71910112,
       20.26966292, 20.82022472, 21.37078652, 21.92134831, 22.47191011,
       23.02247191, 23.57303371, 24.12359551, 24.6741573 , 25.2247191 ,
       25.7752809 , 26.3258427 , 26.87640449, 27.42696629, 27.97752809,
       28.52808989, 29.07865169, 29.62921348, 30.17977528, 30.73033708,
       31.28089888, 31.83146067, 32.38202247, 32.93258427, 33.48314607,
       34.03370787, 34.58426966, 35.13483146, 35.68539326, 36.23595506,
       36.78651685, 37.33707865, 37.88764045, 38.43820225, 38.98

In [54]:
np.linspace(1,50,90,retstep=True)

(array([ 1.        ,  1.5505618 ,  2.1011236 ,  2.65168539,  3.20224719,
         3.75280899,  4.30337079,  4.85393258,  5.40449438,  5.95505618,
         6.50561798,  7.05617978,  7.60674157,  8.15730337,  8.70786517,
         9.25842697,  9.80898876, 10.35955056, 10.91011236, 11.46067416,
        12.01123596, 12.56179775, 13.11235955, 13.66292135, 14.21348315,
        14.76404494, 15.31460674, 15.86516854, 16.41573034, 16.96629213,
        17.51685393, 18.06741573, 18.61797753, 19.16853933, 19.71910112,
        20.26966292, 20.82022472, 21.37078652, 21.92134831, 22.47191011,
        23.02247191, 23.57303371, 24.12359551, 24.6741573 , 25.2247191 ,
        25.7752809 , 26.3258427 , 26.87640449, 27.42696629, 27.97752809,
        28.52808989, 29.07865169, 29.62921348, 30.17977528, 30.73033708,
        31.28089888, 31.83146067, 32.38202247, 32.93258427, 33.48314607,
        34.03370787, 34.58426966, 35.13483146, 35.68539326, 36.23595506,
        36.78651685, 37.33707865, 37.88764045, 38.4

In [57]:
D3 = np.array([[[1,2,3],[4,5,6],[1,2,5]],[[7,8,9],[1,2,4],[7,8,9]]])
D3


array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 5]],

       [[7, 8, 9],
        [1, 2, 4],
        [7, 8, 9]]])

In [91]:
#ravel converts array of any dim to a single (1D )
a2 = np.arange(50).reshape(5,5,2)
a2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [92]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
## create 2d array and convert it into 1 dimesnion

In [94]:
arr = np.arange(10).reshape(5,2)
arr
##arr.ravel()


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [95]:
d2 = np.array([[10,22,31],[13,42,72]])
d2.ravel()


array([10, 22, 31, 13, 42, 72])

In [96]:
a1=np.arange(10).reshape(2,5)
a1


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [97]:
l1=[1,2,3,4]
l2=[5,6,7,8]
l3=[9,10,11,12]
ar1=np.array([l1,l2,l3])
ar1



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
#random->create random nos->rand->(0,1)
np.random.rand(5) 

array([0.49714546, 0.36828226, 0.73098917, 0.41456063, 0.83564321])

In [102]:
np.random.rand(5)*100 ##  broadcasting ## mathematical operation element

array([79.57159246,  7.37061553, 30.86417944, 35.29173712, 57.91863709])

In [ ]:
print(np.random.rand(5)+100)
print(np.random.rand(5)-100)
print(np.random.rand(5)/100)


In [111]:
np.random.randint(10) #within 5 (Exclude) create 1 int random no

1

In [114]:
np.random.randint(1,5)

3

In [118]:
np.random.rand(10).reshape(2,5)

array([[0.01588446, 0.73553857, 0.68288034, 0.86890967, 0.60706353],
       [0.8647772 , 0.47616885, 0.75094802, 0.54306106, 0.37457299]])

In [ ]:
np.linspace(1,5,4,retstep=True)

In [122]:
a=np.linspace(0,50,11,retstep=True,dtype=int)
a

(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50]), 5.0)

In [ ]:
a=np.linspace(1,50,5)

In [ ]:
a

In [ ]:
type(a)

In [ ]:
a=np.linspace(0,50,11)
type(a)
a

In [128]:
b=np.linspace(0,100,10,retstep=True)
b


(array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
         44.44444444,  55.55555556,  66.66666667,  77.77777778,
         88.88888889, 100.        ]),
 11.11111111111111)

In [130]:
np.random.rand(10)+100


array([100.63347097, 100.0144071 , 100.79822899, 100.75933629,
       100.35548906, 100.41641091, 100.03840635, 100.09967811,
       100.04726331, 100.09220997])

In [126]:
np.random.rand(10)+100


array([100.11419744, 100.26830675, 100.68524084, 100.90918915,
       100.94456662, 100.18051364, 100.71000311, 100.44719984,
       100.16899277, 100.6192495 ])

In [132]:
np.random.randint(1,50,10)

array([22, 24, 43,  5, 44, 42, 37, 35, 40, 24])

In [136]:
np.random.randint(100,size=10)


array([ 1, 87, 29, 28,  3, 93, 51, 30, 29, 26])

In [138]:
np.linspace(1,50,17)

array([ 1.    ,  4.0625,  7.125 , 10.1875, 13.25  , 16.3125, 19.375 ,
       22.4375, 25.5   , 28.5625, 31.625 , 34.6875, 37.75  , 40.8125,
       43.875 , 46.9375, 50.    ])

In [144]:
np.random.randint(1,5)

2

## Numpy Array Indexing

In [145]:
## Indexing in 1 Dimension
arr=np.array([1,2,3,4,5,6,7])

In [148]:
print(arr[5])

6


In [149]:
## Indexing in 2 dimension
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [67]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [150]:
print(arr[1,1]) ## first number represents the 1st dimension but it will come with indexs
## i.e 0  means dimension 1 and 1 means dimenison 2.


7


In [151]:
## Indexing in 3 dimensions
arr=np.array([[[1,2,3],[4,5,5],[7,8,9],[10,11,12]]])

In [152]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  5],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [153]:
print(arr[0,3,2])

12


## Numpy Slicing

In [155]:
arr=np.array([1,2,3,4,5,6,7])

In [157]:
print(arr[1:-1])

[2 3 4 5 6]


In [158]:
arr[0:6:2]

array([1, 3, 5])

In [159]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [160]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [83]:
print(arr[1,1:4]) ## mention the dimension and then slicing

[7 8 9]


In [161]:
print(arr[0,1:4])

[2 3 4]


# Stacking
* hstack
* vstack

In [3]:
a1= np.arange(10,50).reshape(10,4)
a1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49]])

In [4]:
a2=np.linspace(10,50,40).reshape(10,4)
a2

array([[10.        , 11.02564103, 12.05128205, 13.07692308],
       [14.1025641 , 15.12820513, 16.15384615, 17.17948718],
       [18.20512821, 19.23076923, 20.25641026, 21.28205128],
       [22.30769231, 23.33333333, 24.35897436, 25.38461538],
       [26.41025641, 27.43589744, 28.46153846, 29.48717949],
       [30.51282051, 31.53846154, 32.56410256, 33.58974359],
       [34.61538462, 35.64102564, 36.66666667, 37.69230769],
       [38.71794872, 39.74358974, 40.76923077, 41.79487179],
       [42.82051282, 43.84615385, 44.87179487, 45.8974359 ],
       [46.92307692, 47.94871795, 48.97435897, 50.        ]])

In [5]:
type(a2)

numpy.ndarray

In [6]:
a2.dtype

dtype('float64')

In [7]:
a1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49]])

In [8]:
a2

array([[10.        , 11.02564103, 12.05128205, 13.07692308],
       [14.1025641 , 15.12820513, 16.15384615, 17.17948718],
       [18.20512821, 19.23076923, 20.25641026, 21.28205128],
       [22.30769231, 23.33333333, 24.35897436, 25.38461538],
       [26.41025641, 27.43589744, 28.46153846, 29.48717949],
       [30.51282051, 31.53846154, 32.56410256, 33.58974359],
       [34.61538462, 35.64102564, 36.66666667, 37.69230769],
       [38.71794872, 39.74358974, 40.76923077, 41.79487179],
       [42.82051282, 43.84615385, 44.87179487, 45.8974359 ],
       [46.92307692, 47.94871795, 48.97435897, 50.        ]])

In [9]:
np.hstack((a1,a2))    #1st hori col of 1st array and 2nd array get merged into one single []
#stack() needs a list or tuple to be passed in. needs [] or () hence, 2 ()

array([[10.        , 11.        , 12.        , 13.        , 10.        ,
        11.02564103, 12.05128205, 13.07692308],
       [14.        , 15.        , 16.        , 17.        , 14.1025641 ,
        15.12820513, 16.15384615, 17.17948718],
       [18.        , 19.        , 20.        , 21.        , 18.20512821,
        19.23076923, 20.25641026, 21.28205128],
       [22.        , 23.        , 24.        , 25.        , 22.30769231,
        23.33333333, 24.35897436, 25.38461538],
       [26.        , 27.        , 28.        , 29.        , 26.41025641,
        27.43589744, 28.46153846, 29.48717949],
       [30.        , 31.        , 32.        , 33.        , 30.51282051,
        31.53846154, 32.56410256, 33.58974359],
       [34.        , 35.        , 36.        , 37.        , 34.61538462,
        35.64102564, 36.66666667, 37.69230769],
       [38.        , 39.        , 40.        , 41.        , 38.71794872,
        39.74358974, 40.76923077, 41.79487179],
       [42.        , 43.        

In [10]:
np.vstack((a1,a2)) #stacks a2 after stacking a1 

array([[10.        , 11.        , 12.        , 13.        ],
       [14.        , 15.        , 16.        , 17.        ],
       [18.        , 19.        , 20.        , 21.        ],
       [22.        , 23.        , 24.        , 25.        ],
       [26.        , 27.        , 28.        , 29.        ],
       [30.        , 31.        , 32.        , 33.        ],
       [34.        , 35.        , 36.        , 37.        ],
       [38.        , 39.        , 40.        , 41.        ],
       [42.        , 43.        , 44.        , 45.        ],
       [46.        , 47.        , 48.        , 49.        ],
       [10.        , 11.02564103, 12.05128205, 13.07692308],
       [14.1025641 , 15.12820513, 16.15384615, 17.17948718],
       [18.20512821, 19.23076923, 20.25641026, 21.28205128],
       [22.30769231, 23.33333333, 24.35897436, 25.38461538],
       [26.41025641, 27.43589744, 28.46153846, 29.48717949],
       [30.51282051, 31.53846154, 32.56410256, 33.58974359],
       [34.61538462, 35.

In [12]:
#Create 2 arrays, 1st array->15(0-14) 2nd array->15(20-34)
# Use hstack and vstack
ab1=np.arange(15).reshape(5,3)
ab2=np.arange(20,35).reshape(5,3)
print(ab1)
print(ab2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]]


In [13]:
np.hstack((ab1,ab2))

array([[ 0,  1,  2, 20, 21, 22],
       [ 3,  4,  5, 23, 24, 25],
       [ 6,  7,  8, 26, 27, 28],
       [ 9, 10, 11, 29, 30, 31],
       [12, 13, 14, 32, 33, 34]])

In [ ]:
np.vstack((ab1,ab2))

In [ ]:
np.hstack((ab1,ab2,ab1))

In [ ]:
a = np.arange(15).reshape(3,5)
a

In [ ]:
#Split->hsplit,vsplit
ab1

In [ ]:
ab2

In [14]:
np.hsplit(ab1,3)    #cut the array horrizontally into no. of col (3) - gives 3 arrays

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]])]

In [15]:
np.vsplit(ab1,5)     #cut the array vertically into no. of rows (5) - gives 5 arrays

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]]),
 array([[12, 13, 14]])]

In [ ]:
a3=np.arange(24).reshape(6,4)
a3

In [ ]:
np.hsplit(a3,2)

In [ ]:
np.hsplit(a3,4)

In [ ]:
a3

In [ ]:
np.vsplit(a3,3)

In [ ]:
np.vsplit(a3,2)

In [ ]:
np.vsplit(a3,6)

In [ ]:
a10 = np.arange(24).reshape(2,3,4)
a11= np.hsplit(a10,3)
print(a10)
print(a11)


In [162]:
# Broadcasting 
a3=np.arange(24).reshape(6,4)
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [163]:
a3*10

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110],
       [120, 130, 140, 150],
       [160, 170, 180, 190],
       [200, 210, 220, 230]])

In [165]:
## changing the values of array element
a3[0:2,]=10

In [166]:
a3

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [167]:
a3[4:,1:3]
a3

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
ab1

In [ ]:
# 2nd & 3rd column replace with 100
ab1[:,1:3] = 100
ab1

In [ ]:
ab1[4:,2:] = 50
ab1

In [16]:
# Boolean Masking
ab1 = np.arange(15).reshape(5,3)
ab1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
#Name = o/p wanted == condition  SYNTAX
re = 0 == ab1%2 # re= ab1%2==0 takes element where remainder=0    
#re is user-defined name   

In [ ]:
ab1[re]

In [ ]:
re

In [ ]:
re1 = 0 == ab1%3
re1

In [ ]:
## Copy operation ## used as backup
 array,pandas,csv files ,excels ,database,when we doing data preprocessing-->???


In [169]:
#zeros,ones,eye,max,min,copy
np.zeros(2) ## 1 d array with 2 elements and each element is 0

array([0., 0.])

In [171]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [173]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [174]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [175]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [176]:
ab1=np.arange(15).reshape(5,3)

In [177]:
ab1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [178]:
np.max(ab1)

14

In [179]:
np.min(ab1)

0

In [180]:
np.sum(ab1)

105

In [ ]:
ab3=ab1.copy()
ab3

In [182]:
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [ ]:
ab4=ab1

In [ ]:
ab4

In [ ]:
ab1

In [ ]:
ab4

In [ ]:
b=ab1+ab4
b

In [ ]:
c=ab1-ab4
c